//
//  BIOCaptureHandlerError.h
//  BiometricSDK
//
//  Created by WASAG Kamil - EXT-REPERIO (MORPHO) on 14/04/2016.
//  Copyright © 2016 WASAG Kamil - EXT-REPERIO (MORPHO). All rights reserved.
//

NS_ASSUME_NONNULL_BEGIN

extern NSString * const BIOUserInfoKeyLockedUntil;

extern NSErrorDomain const BIOCaptureHandlerErrorDomain;

typedef int BIOCaptureHandlerError;

extern const BIOCaptureHandlerError BIOCaptureHandlerErrorSuccess;
extern const BIOCaptureHandlerError BIOCaptureHandlerErrorParameters;
extern const BIOCaptureHandlerError BIOCaptureHandlerErrorParameterUnknown;
extern const BIOCaptureHandlerError BIOCaptureHandlerErrorMemAlloc;
extern const BIOCaptureHandlerError BIOCaptureHandlerErrorInit;
extern const BIOCaptureHandlerError BIOCaptureHandlerErrorGraphInitialisationFailed;
extern const BIOCaptureHandlerError BIOCaptureHandlerErrorParameterNotFound;
extern const BIOCaptureHandlerError BIOCaptureHandlerErrorParameterSize;
extern const BIOCaptureHandlerError BIOCaptureHandlerErrorTypeMismatch;
extern const BIOCaptureHandlerError BIOCaptureHandlerErrorInvalidHandle;
extern const BIOCaptureHandlerError BIOCaptureHandlerErrorLicense;
extern const BIOCaptureHandlerError BIOCaptureHandlerErrorAppliNotAvailable;
extern const BIOCaptureHandlerError BIOCaptureHandlerErrorProfileNotAvailable;
extern const BIOCaptureHandlerError BIOCaptureHandlerErrorSubprofileNotAvailable;
extern const BIOCaptureHandlerError BIOCaptureHandlerErrorUnknown;
extern const BIOCaptureHandlerError BIOCaptureHandlerErrorInvalidOperation;
extern const BIOCaptureHandlerError BIOCaptureHandlerErrorIncompatibleApiVersion;
extern const BIOCaptureHandlerError BIOCaptureHandlerErrorCameraError;
extern const BIOCaptureHandlerError BIOCaptureHandlerErrorParameterWrongType;
extern const BIOCaptureHandlerError BIOCaptureHandlerErrorParameterNotSet;
extern const BIOCaptureHandlerError BIOCaptureHandlerErrorInvalidPluginsConfiguration;
extern const BIOCaptureHandlerError BIOCaptureHandlerErrorParameterWrongValue;
extern const BIOCaptureHandlerError BIOCaptureHandlerErrorCaptureIsLocked;
extern const BIOCaptureHandlerError BIOCaptureHandlerErrorSignatureVerificationFailed;
extern const BIOCaptureHandlerError BIOCaptureHandlerErrorVideoGenerationInProgress;
extern const BIOCaptureHandlerError BIOCaptureHandlerErrorSignatureVerificationFailed;

NSString * NSStringFromBIOCaptureHandlerError(BIOCaptureHandlerError error);

NS_ASSUME_NONNULL_END
